routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');

Route::group(['prefix' => 'account'], function () {
    Auth::routes(['register' => false]);
});


Route::group(['middleware' => 'auth'], function () {
    // users
    Route::group(['prefix' => 'company', 'as' => 'company.'], function () {
        Route::resource('member', 'User\UserController');
        Route::get('department/{departmentId}', 'User\UserController@index');
    });

    // BMS
    Route::group(['prefix' => 'mbs', 'as' => 'mbs.'], function () {
        // Home
        Route::get('/', ['as' => 'home.index', 'uses' => 'Mbs\HomeController@index']);
        Route::get('/init-contact', 'Mbs\HomeController@initContact');
        Route::get('/init-history-contact', 'Mbs\HomeController@initHistoryContact');
        Route::get('/load-message', 'Mbs\HomeController@loadMessage');
        Route::post('/load-contact', 'Mbs\HomeController@loadContact');
        Route::post('store', 'Mbs\HomeController@store');
        Route::resource('group-custom', 'Mbs\CustomGroupController');
        Route::resource('user-custom', 'Mbs\CustomUserController');
    });
});

app/Models/Mbs/MbsContactGroupCustom.php
<?php

namespace App\Models\Mbs;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class MbsContactGroupCustom
 * @package App\Models\Mbs
 */
class MbsContactGroupCustom extends Model
{
    use SoftDeletes;

    /**
     * @var string
     */
    public $table = 'mbs_contact_group_custom';

    /**
     * @var array
     */
    public $fillable = [
        'name',
        'detail',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'name' => 'string',
        'detail' => 'string',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function groupCustomUserList(){
        return $this->hasMany(
            'App\Models\Mbs\MbsContactGroupCustomUserList',
            'custom_group_id',
            'id'
        );
    }
}

app/Models/Mbs/MbsContactGroupCustomUserList.php
<?php

namespace App\Models\Mbs;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class MbsContactGroupCustomUserList
 * @package App\Models\Mbs
 */
class MbsContactGroupCustomUserList extends Model
{
    use SoftDeletes;

    /**
     * @var string
     */
    public $table = 'mbs_contact_group_custom_user_list';

    /**
     * @var array
     */
    public $fillable = [
        'custom_group_id',
        'contact_id',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'custom_group_id' => 'integer',
        'contact_id' => 'string',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];


}

app/Models/Mbs/MbsGroup.php
<?php

namespace App\Models\Mbs;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class MbsGroup
 * @package App\Models\Mbs
 */
class MbsGroup extends Model
{
    use SoftDeletes;

    /**
     * @var string
     */
    public $table = 'mbs_group';

    /**
     * @var array
     */
    public $fillable = [
        'group_id',
        'contact_id',
        'total',
        'user_id',
        'position_id',
        'department_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'group_id' => 'integer',
        'contact_id' => 'string',
        'total' => 'integer',
        'user_id' => 'integer',
        'position_id' => 'integer',
        'department_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];


}

app/Models/Mbs/MbsMessage.php
<?php

namespace App\Models\Mbs;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class MbsMessage
 * @package App\Models\Mbs
 */
class MbsMessage extends Model
{
    use SoftDeletes;

    /**
     * @var string
     */
    public $table = 'mbs_messages';

    /**
     * @var array
     */
    public $fillable = [
        'title',
        'detail',
        'type',
        'user_id',
        'position_id',
        'department_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'title' => 'string',
        'detail' => 'string',
        'type' => 'string',
        'created_at' => 'datetime:d/m/Y H:i',
        'user_id' => 'integer',
        'position_id' => 'integer',
        'department_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function files(){
        return $this->hasMany(
            'App\Models\Mbs\MbsMessageFiles',
            'message_id',
            'id'
        );
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function userProfile(){
        return $this->belongsTo(
            'App\Models\User\User',
            'user_id',
            'id'
        );
    }


}

app/Models/Mbs/MbsMessageFiles.php
<?php

namespace App\Models\Mbs;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class MbsMessageFiles
 * @package App\Models\Mbs
 */
class MbsMessageFiles extends Model
{
    use SoftDeletes;

    /**
     * @var string
     */
    public $table = 'mbs_messages_files';

    /**
     * @var array
     */
    public $fillable = [
        'uid',
        'message_id',
        'file_type',
        'file_name',
        'file_name_old',
        'file_path',
        'user_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'uid' => 'string',
        'message_id' => 'integer',
        'file_type' => 'string',
        'file_name' => 'string',
        'file_name_old' => 'string',
        'file_path' => 'string',
        'user_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

}

app/Models/Mbs/MbsUserCustom.php
<?php

namespace App\Models\Mbs;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class MbsUserCustom
 * @package App\Models\Mbs
 */
class MbsUserCustom extends Model
{
    use SoftDeletes;

    /**
     * @var string
     */
    public $table = 'mbs_users_custom';

    /**
     * @var array
     */
    public $fillable = [
        'name',
        'password_rand',
        'detail',
        'activated'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'name' => 'string',
        'password' => 'string',
        'detail' => 'string',
        'activated' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];


}

app/Http/Controllers/Mbs/CustomGroupController.php
<?php

namespace App\Http\Controllers\Mbs;


use App\Http\Controllers\Controller;
use App\Models\Mbs\MbsContactGroupCustom;
use App\Models\Mbs\MbsGroup;
use App\Models\Mbs\MbsMessageList;
use App\Models\Mbs\MbsUserCustom;
use App\Models\User\Department;
use App\Models\User\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Carbon;

/**
 * Class CustomGroupController
 * @package App\Http\Controllers\Modules\mbs
 */
class CustomGroupController extends Controller
{

    /**
     * Display a listing of the Division.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {

        $model = MbsContactGroupCustom::paginate(50);

        return view('mbs.custom_group.index', compact('model'));
    }

    /**
     * @return array
     */
    public function groupTypeList(){

        $departments = Department::getDepartmentList();

        $groupCustom = MbsContactGroupCustom::get(['name', 'id'])->toArray();

        $users = User::userActive()->get(['name', 'id'])->toArray();

        $userCustom = MbsUserCustom::get(['name', 'id'])->toArray();

        $departmentList = [];
        foreach ($departments as $k => $v){
            $departmentList['d'.$k] = $v;
        }

        $groupCustomList = [];
        foreach ($groupCustom as $k => $v){
            $groupCustomList['g'.$v['id']] = $v['name'];
        }

        $usersList = [];
        foreach ($users as $k => $v){
            $usersList['u'.$v['id']] = $v['name'];
        }

        $usersCustomList = [];
        foreach ($userCustom as $k => $v){
            $usersCustomList['c'.$v['id']] = $v['name'];
        }

        $contacts = [
            'แผนก/ฝ่าย' => $departmentList,
            'กลุ่มอื่น ๆ' => $groupCustomList,
            'ผู้ใช้งาน' => $usersList,
            'ผู้ใช้งานพิเศษ' => $usersCustomList
        ];

        return $contacts;
    }

    /**
     * @param $model MbsContactGroupCustom
     * @return mixed MbsContactGroupCustom
     */
    protected function loadForm($model){

        $contacts = $this->groupTypeList();

        $model->setAttribute('contact_type_id', $contacts);

        return $model;
    }

    /**
     * Show the form for creating a new Division.
     *
     * @return Response
     */
    public function create()
    {
        $model = new MbsContactGroupCustom();

        $model = $this->loadForm($model);

        return view('mbs.custom_group.create', compact('model'));
    }

    /**
     * Store a newly created Division in storage.
     *
     * @param Request $request
     *
     * @return Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'name'=>'required|max:255',
            'contact_type_id' => 'required'
        ]);

        $input = $request->all();

        $model = MbsContactGroupCustom::create($input);

        if(!empty($model->id)){

            $now = Carbon::now();
            $groupCustomUserList = [];
            foreach ($input['contact_type_id'] as $value) {
                $groupCustomUserList[] = [
                    'custom_group_id' =>  $model->id,
                    'contact_id' => $value,
                    'created_at' => $now
                ];
            }

            $model->groupCustomUserList()->insert($groupCustomUserList);
        }

        return redirect(route('mbs.group-custom.index'))
            ->with('success', 'Created Division: Success!');
    }

    /**
     * Display the specified Division.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        return redirect(route('mbs.group-custom.edit', compact('id')));
    }

    /**
     * Show the form for editing the specified Division.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {

        $model = MbsContactGroupCustom::with(['groupCustomUserList'])->findOrFail($id);

        $model = $this->loadForm($model);

        $model->setAttribute('groupCustomUserList', $model->groupCustomUserList->pluck('contact_id'));

        return view('mbs.custom_group.edit', compact('model'));
    }

    /**
     * Update the specified Division in storage.
     *
     * @param int $id
     * @param Request $request
     *
     * @return Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update($id, Request $request)
    {

        $this->validate($request, [
            'name' => 'required|max:255',
            'contact_type_id' => 'required'
        ]);

        $model = MbsContactGroupCustom::findOrFail($id);

        $input = $request->all();

        $model->fill($input);

        $model->save();

        if(!empty($model->id)){

            $now = Carbon::now();
            $groupCustomUserList = [];
            foreach ($input['contact_type_id'] as $value) {
                $groupCustomUserList[] = [
                    'custom_group_id' => $model->id,
                    'contact_id' => $value,
                    'created_at' => $now
                ];
            }

            $model->groupCustomUserList()->where('custom_group_id', $model->id)->forceDelete();
            $model->groupCustomUserList()->insert($groupCustomUserList);
        }

        return redirect(route('mbs.group-custom.edit', compact('id')))
            ->with('success', 'Updated Division: Success!');
    }

    /**
     * Remove the specified Division from storage.
     *
     * @param int $id
     *
     * @return array|Response
     * @throws \Exception
     */
    public function destroy($id)
    {
        $model = MbsContactGroupCustom::findOrFail($id);

        $model->delete();

        $model->groupCustomUserList()->where('custom_group_id', $id)->forceDelete();

        $contactId = "g{$id}";

        $groupIdList = MbsGroup::where('contact_id', $contactId)->where('total', 1)->pluck('group_id')->toArray();
        if(count($groupIdList)){
            MbsMessageList::whereIn('group_id', $groupIdList)->delete();
        }

        $groupIdList = MbsGroup::where('contact_id', $contactId)->pluck('group_id')->toArray();
        MbsGroup::whereIn('group_id', $groupIdList)->decrement('total', 1);
        MbsGroup::where('contact_id', $contactId)->delete();

        return [
            'success' => true,
            'data'    => $id,
            'message' => 'User Group deleted successfully'
        ];
    }
}

app/Http/Controllers/Mbs/CustomUserController.php
<?php

namespace App\Http\Controllers\Mbs;

use App\Http\Controllers\Controller;
use App\Models\Mbs\MbsGroup;
use App\Models\Mbs\MbsMessageList;
use App\Models\Mbs\MbsUserCustom;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

/**
 * Class CustomUserController
 * @package App\Http\Controllers\Mbs
 */
class CustomUserController extends Controller
{
    /**
     * Display a listing of the CustomUserController.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {

        $model = MbsUserCustom::paginate(50);

        return view('mbs.custom_user.index', compact('model'));
    }

    /**
     * Show the form for creating a new Division.
     *
     * @return Response
     */
    public function create()
    {
        $model = new MbsUserCustom();

        return view('mbs.custom_user.create', compact('model'));
    }

    /**
     * Store a newly created Division in storage.
     *
     * @param Request $request
     *
     * @return Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'name'=>'required|max:255',
            'password_rand' => 'required|min:6|max:6|unique:mbs_users_custom'
        ]);

        $input = $request->all();

        $model = MbsUserCustom::create($input);

        return redirect(route('mbs.user-custom.index'))
            ->with('success', 'Created Division: Success!');
    }

    /**
     * Display the specified Division.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        return redirect(route('mbs.user-custom.edit', compact('id')));
    }

    /**
     * Show the form for editing the specified Division.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {

        $model = MbsUserCustom::findOrFail($id);

        return view('mbs.custom_user.edit', compact('model'));
    }

    /**
     * Update the specified Division in storage.
     *
     * @param int $id
     * @param Request $request
     *
     * @return Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update($id, Request $request)
    {

        $this->validate($request, [
            'name'=>'required|max:255'
        ]);

        $model = MbsUserCustom::findOrFail($id);

        $input = $request->only('name');

        $model->fill($input);

        $model->save();

        return redirect(route('mbs.user-custom.edit', compact('id')))
            ->with('success', 'Updated Division: Success!');
    }

    /**
     * Remove the specified Division from storage.
     *
     * @param int $id
     *
     * @return array|Response
     * @throws \Exception
     */
    public function destroy($id)
    {
        $model = MbsUserCustom::findOrFail($id);

        $model->delete();

        $contactId = "c{$id}";

        $groupIdList = MbsGroup::where('contact_id', $contactId)->where('total', 1)->pluck('group_id')->toArray();
        if(count($groupIdList)){
            MbsMessageList::whereIn('group_id', $groupIdList)->delete();
        }

        $groupIdList = MbsGroup::where('contact_id', $contactId)->pluck('group_id')->toArray();
        MbsGroup::whereIn('group_id', $groupIdList)->decrement('total', 1);
        MbsGroup::where('contact_id', $contactId)->delete();

        return [
            'success' => true,
            'data'    => $id,
            'message' => 'User Group deleted successfully'
        ];
    }
}

resources/views/mbs/custom_group/create.blade.php
@extends('mbs._layout')

@section('title')
    Message Broadcast System (MBS)
@endsection

@push('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet" />
    <style>
        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            background: #009efb;
            color: #fff;
        }
        .select2-container--default .select2-selection--multiple .select2-selection__choice__remove {
            color: #fff;
        }
        .select2-container--default .select2-results>.select2-results__options {
            max-height: 350px;
        }
    </style>
@endpush

@section('mbs_content')
    <div class="card mb-0">
        <div class="card-body">
            <h4 class="card-title">เพิ่มกลุ่มผู้รับข้อความ</h4>
            <hr>

            @include ('errors.list')

            {!! Form::open(['route' => 'mbs.group-custom.store']) !!}
            @include('mbs.custom_group.fields')
            {!! Form::close() !!}

        </div>
    </div>
@endsection

@push('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
<script src="https://malsup.github.io/jquery.blockUI.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script>
    $('#contact_type_id').select2();
</script>
@endpush

resources/views/mbs/custom_group/edit.blade.php
@extends('mbs._layout')

@section('title')
    Message Broadcast System (MBS)
@endsection

@push('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet" />
    <style>
        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            background: #009efb;
            color: #fff;
        }
        .select2-container--default .select2-selection--multiple .select2-selection__choice__remove {
            color: #fff;
        }
        .select2-container--default .select2-results>.select2-results__options {
            max-height: 350px;
        }
    </style>
@endpush

@section('mbs_content')
    <div class="card mb-0">
        <div class="card-body">
            <h4 class="card-title">Edit กลุ่มผู้รับข้อความ</h4>
            <hr>

            @include ('errors.list')

            {!! Form::model($model, ['route' => ['mbs.group-custom.update', $model->id], 'method' => 'patch']) !!}
            @include('mbs.custom_group.fields')
            {!! Form::close() !!}

        </div>
    </div>
@endsection

@push('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
<script src="https://malsup.github.io/jquery.blockUI.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script>
    $('#contact_type_id').select2();
</script>
@endpush

resources/views/mbs/custom_group/fields.blade.php
<div class="row">
    <!-- Name Field -->
    <div class="form-group col-md-12">
        {!! Form::label('contact_type_id', 'ผู้ติดต่อ:') !!}
        {!! Form::select('contact_type_id[]', $model->contact_type_id, $model->groupCustomUserList, ['class' => 'form-control', 'multiple' => true, 'id' => 'contact_type_id', 'style' => 'width:100%;']) !!}
    </div>

    <!-- Code Field -->
    <div class="form-group col-md-12">
        {!! Form::label('name', 'ชื่อกลุ่ม:') !!}
        {!! Form::text('name', $model->name ?? old('name'), ['class' => 'form-control']) !!}
    </div>

    <!-- Name Field -->
    <div class="form-group col-md-12">
        {!! Form::label('detail', 'รายละเอียด (ไม่บังคับ):') !!}
        {!! Form::textarea('detail', $model->detail ?? old('detail'), ['class' => 'form-control']) !!}
    </div>

    <!-- Submit Field -->
    <div class="col-md-12">
        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
        <a href="{!! route('mbs.group-custom.index') !!}" class="btn btn-danger">Cancel</a>
    </div>
</div>

resources/views/mbs/custom_group/index.blade.php
@extends('mbs._layout')

@section('title')
    Message Broadcast System (MBS)
@endsection

@section('mbs_content')
    <div class="card mb-0">
        <div class="card-body">
            <h4 class="card-title">กลุ่มผู้รับข้อความ</h4>

            <div class="float-right mb-3">
                <a href="{!! route('mbs.group-custom.create') !!}" class="btn btn-success btn-rounded"><i class="ti ti-plus"></i> สร้างกลุ่มใหม่</a>
            </div>

            @include('mbs.custom_group.table')

            {{ $model->links() }}
        </div>
    </div>
@endsection

@push('js')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script>
    $('.confirm-remove').click(function(){
        var url = $(this).attr('data-action');
        var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
        Swal.fire({
            title: "คุณต้องการลบข้อมูลหรือใม่ ?",
            text: "ยืนยันการลบข้อมูลนี้ออก",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "ยืนยัน",
            cancelButtonText: "ยกเลิก",
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    url: url,
                    type: 'DELETE',
                    data: {_token: CSRF_TOKEN},
                    dataType: 'JSON',
                    success: function(result) {
                        $('#data-row-' + result.data).fadeOut();
                        Swal.fire(
                            'ลบข้อมูลเรียบร้อย!',
                            result.message, "success"
                        )
                    }
                });
            }
        });
    });
</script>
@endpush

resources/views/mbs/custom_group/show.blade.php
@extends('layouts.theme.elegant.layout')

@section('title', 'Division')

@section('page_name')
    Division
@endsection

@section('breadcrumb_top')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/home') }}">Home</a></li>
        <li class="breadcrumb-item"><a href="{{ url('/home') }}">company.</a></li>
        <li class="breadcrumb-item"><a href="{{ route('division.index') }}">Divisions</a></li>
        <li class="breadcrumb-item active">{{ $division->name }}</li>
    </ol>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="m-b-10">
                    <a href="{!! route('division.index') !!}" class="btn btn-success btn-rounded"><i class="ti-control-backward"></i> Back</a>
                </div>
                <hr>
                <h4 class="card-title">{{ $division->name }}</h4>
                @include('company.departments.table_data')
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mbs/custom_group/show_fields.blade.php
<!-- Id Field -->
<div class="col-md-12">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $division->id !!}</p>
</div>

<!-- Code Field -->
<div class="col-md-12">
    {!! Form::label('code', 'Code:') !!}
    <p>{!! $division->code !!}</p>
</div>

<!-- Name Field -->
<div class="col-md-12">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $division->name !!}</p>
</div>

<!-- Created At Field -->
<div class="col-md-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $division->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="col-md-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $division->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="col-md-12">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $division->deleted_at !!}</p>
</div>

resources/views/mbs/custom_group/table.blade.php
<div class="table-responsive">
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Detail</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($model as $data)
            <tr id="data-row-{{ $data->id }}">
                <td>{!! $data->name !!}</td>
                <td>{!! $data->detail !!}</td>
                <td>
                    <div>
                        <a href="{!! route('mbs.group-custom.edit', [$data->id]) !!}" class='btn btn-success btn-sm m-r-5'><i class="ti ti-pencil-alt"></i> Edit</a>
                        {!! Form::button('<i class="ti ti-trash"></i> Delete', ['class' => 'btn btn-sm btn-danger confirm-remove', 'data-action' => route('mbs.group-custom.destroy', $data->id)]) !!}
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>